[package]
name = "google-drive"
version = "0.1.0"
edition = "2024"

[dependencies]
google-drive3 = "7.0.0"
hyper = "1.8.1"
hyper-rustls = "0.27.7"
serde = "1.0.228"
serde_json = "1.0.149"
tokio = "1.49.0"
yup-oauth2 = "12.1.2"
